/* Copyright (c) Neo
   Licensed under the MIT License. */

// This file defines the mapping from the MT3620 reference development board (RDB) to the
// 'sample hardware' abstraction used by the samples at https://github.com/xiongyu0523/azure-sphere-arducam-mini-2mp-plus.
// Some peripherals are on-board on the RDB, while other peripherals must be attached externally if needed.
// See https://docs.microsoft.com/en-us/azure-sphere/app-development/manage-hardware-dependencies for more information on how to use hardware abstractions
// to enable apps to work across multiple hardware variants.

// This file is autogenerated from ../../sample_hardware.json.  Do not edit it directly.

#pragma once
#include "mt3620_rdb.h"

// Connect CS to RDB Header1 Pin10(GPIO3)
#define ARDUCAM_CS MT3620_RDB_HEADER1_PIN10_GPIO

// Connect I2C to RDB Header2 Pin1(SDA) and Pin7(SCL)
#define ARDUCAM_I2C MT3620_RDB_HEADER2_ISU0_I2C

// Connect SPI to RDB Header4 Pin5(MISO), Pin7(SCLK), Pin11(MOSI)
#define ARDUCAM_SPI MT3620_RDB_HEADER4_ISU1_SPI

// Connect RST to RDB Header1 Pin4(GPIO0)
#define ILI9341_RST MT3620_RDB_HEADER1_PIN4_GPIO

// Connect DC to RDB Header1 Pin6(GPIO1)
#define ILI9341_DC MT3620_RDB_HEADER1_PIN6_GPIO

// Connect BL to RDB Header1 Pin8(GPIO2)
#define ILI9341_BL MT3620_RDB_HEADER1_PIN8_GPIO

// Connect SPI to RDB Header3 Pin5(SCLK), Pin7(MOSI), Pin9(MISO), Pin11(CSA)
#define ILI9341_SPI MT3620_RDB_HEADER3_ISU3_SPI

// Connect Test IO 0 to RDB Header1 Pin12(GPIO4)
#define TESTIO_0 MT3620_RDB_HEADER1_PIN12_GPIO

// Connect Test IO 1 to RDB Header2 Pin4(GPIO5)
#define TESTIO_1 MT3620_RDB_HEADER2_PIN4_GPIO

// Connect Test IO 2 to RDB Header2 Pin6(GPIO6)
#define TESTIO_2 MT3620_RDB_HEADER2_PIN6_GPIO

// Connect Test IO 2 to RDB Header2 Pin8(GPIO7)
#define TESTIO_3 MT3620_RDB_HEADER2_PIN8_GPIO

